"""phase2_initial_schema

Revision ID: 48d7416982aa
Revises: bd3311e2b2a7
Create Date: 2026-03-17 23:25:07.364304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d7416982aa'
down_revision: Union[str, None] = 'bd3311e2b2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('retrieved_sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_query_logs_id'), 'ai_query_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_query_logs_session_id'), 'ai_query_logs', ['session_id'], unique=False)
    op.create_table('insurance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('insurer_name', sa.String(length=100), nullable=False),
    sa.Column('policy_type', sa.Enum('COMPREHENSIVE', 'THIRD_PARTY', 'STANDALONE_OD', name='policy_type_enum'), nullable=False),
    sa.Column('premium_min', sa.Float(), nullable=False),
    sa.Column('premium_max', sa.Float(), nullable=False),
    sa.Column('coverage_amount', sa.Float(), nullable=False),
    sa.Column('claim_settlement_ratio', sa.Float(), nullable=True),
    sa.Column('add_ons', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policies_id'), 'insurance_policies', ['id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_insurer_name'), 'insurance_policies', ['insurer_name'], unique=False)
    op.create_index(op.f('ix_insurance_policies_name'), 'insurance_policies', ['name'], unique=False)
    op.create_index(op.f('ix_insurance_policies_policy_type'), 'insurance_policies', ['policy_type'], unique=False)
    op.create_table('user_recommendation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('car_model', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('coverage_preference', sa.String(length=50), nullable=True),
    sa.Column('recommended_policy_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recommendation_requests_id'), 'user_recommendation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_user_recommendation_requests_session_id'), 'user_recommendation_requests', ['session_id'], unique=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_user_recommendation_requests_session_id'), table_name='user_recommendation_requests')
    op.drop_index(op.f('ix_user_recommendation_requests_id'), table_name='user_recommendation_requests')
    op.drop_table('user_recommendation_requests')
    op.drop_index(op.f('ix_insurance_policies_policy_type'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_name'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_insurer_name'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_id'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index(op.f('ix_ai_query_logs_session_id'), table_name='ai_query_logs')
    op.drop_index(op.f('ix_ai_query_logs_id'), table_name='ai_query_logs')
    op.drop_table('ai_query_logs')
    # ### end Alembic commands ###
